AWSTemplateFormatVersion: '2010-09-09'
Description: 'Recursos de Red para Pipeline de Datos Serverless - AWS Academy'

Parameters:
  VpcCidr:
    Type: String
    Description: CIDR block para la VPC
    Default: 10.0.0.0/16
    
  PublicSubnetCidr:
    Type: String
    Description: CIDR block para la subred pública
    Default: 10.0.1.0/24
    
  PrivateSubnetCidr:
    Type: String
    Description: CIDR block para la subred privada
    Default: 10.0.2.0/24

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-VPC
        - Key: Project
          Value: data-pipeline

  # Internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-IGW
        - Key: Project
          Value: data-pipeline

  # Attach Internet Gateway to VPC
  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC

  # Public Subnet
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCidr
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Public-Subnet
        - Key: Project
          Value: data-pipeline

  # Private Subnet
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Private-Subnet
        - Key: Project
          Value: data-pipeline

  # Route Tables
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Public-RT
        - Key: Project
          Value: data-pipeline

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-Private-RT
        - Key: Project
          Value: data-pipeline

  # Routes
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  # Nota: Ruta privada eliminada ya que no hay NAT Gateway

  # Route Table Associations
  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  # Nota: Security Group para Lambda eliminado ya que las Lambdas están fuera de VPC

Outputs:
  VPCId:
    Description: ID de la VPC creada
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPC-ID

  PublicSubnetId:
    Description: ID de la subred pública
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub ${AWS::StackName}-Public-Subnet-ID

  PrivateSubnetId:
    Description: ID de la subred privada
    Value: !Ref PrivateSubnet
    Export:
      Name: !Sub ${AWS::StackName}-Private-Subnet-ID

  InternetGatewayId:
    Description: ID del Internet Gateway
    Value: !Ref InternetGateway
    Export:
      Name: !Sub ${AWS::StackName}-IGW-ID 